/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabajo;

import com.systemjaade.edad.util.DateUtils;
import java.time.LocalDate;
import java.time.Period;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author Rawl
 */
public class AgregarAdmi extends javax.swing.JPanel {

    /**
     * Creates new form AgregarAdmi
     */
    
    public AgregarAdmi() {
        initComponents();
        PanelDA.setVisible(false);
        BtnNuevo.setVisible(false);
        BtnGenerar.setVisible(false);
        BtnGuardar.setVisible(false);
        PassNO.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TextName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextApe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextDNI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TextCel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BtnGenerar = new javax.swing.JButton();
        jDCFecha = new com.toedter.calendar.JDateChooser();
        jTFEdad = new javax.swing.JTextField();
        BtnNuevo = new javax.swing.JButton();
        PanelDA = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TextUser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JButton();
        TextPass = new javax.swing.JPasswordField();
        PassNO = new javax.swing.JLabel();
        TextPassOK = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 6, 12));
        setMaximumSize(new java.awt.Dimension(700, 570));
        setMinimumSize(new java.awt.Dimension(700, 570));
        setPreferredSize(new java.awt.Dimension(700, 570));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelDP.setBackground(new java.awt.Color(0, 0, 0,100));
        PanelDP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS PERSONALES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria Math", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombres");

        TextName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellidos");

        TextApe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextApe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextApeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DNI");

        TextDNI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDNIActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("F. Nacimiento");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");

        TextEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEmailActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Celular");

        TextCel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCelActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Edad");

        BtnGenerar.setBackground(new java.awt.Color(0, 255, 102));
        BtnGenerar.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        BtnGenerar.setText("GENERAR");
        BtnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGenerarActionPerformed(evt);
            }
        });

        jDCFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jDCFecha.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDCFechaPropertyChange(evt);
            }
        });

        jTFEdad.setEditable(false);
        jTFEdad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFEdad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTFEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFEdadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDPLayout = new javax.swing.GroupLayout(PanelDP);
        PanelDP.setLayout(PanelDPLayout);
        PanelDPLayout.setHorizontalGroup(
            PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDPLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDPLayout.createSequentialGroup()
                        .addGroup(PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(175, 541, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDPLayout.createSequentialGroup()
                        .addGroup(PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDPLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelDPLayout.createSequentialGroup()
                                        .addComponent(TextCel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(109, 109, 109)
                                        .addComponent(jTFEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PanelDPLayout.createSequentialGroup()
                                .addGroup(PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelDPLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(TextApe, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelDPLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(TextName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelDPLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18))
                                    .addGroup(PanelDPLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(jDCFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(33, 33, 33))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        PanelDPLayout.setVerticalGroup(
            PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(TextDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TextCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTFEdad))
                .addGap(18, 18, 18)
                .addGroup(PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnGenerar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(PanelDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 11, -1, -1));

        BtnNuevo.setBackground(new java.awt.Color(255, 255, 255));
        BtnNuevo.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        BtnNuevo.setText("NUEVO");
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });
        add(BtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 474, -1, -1));

        PanelDA.setBackground(new java.awt.Color(0, 0, 0,100));
        PanelDA.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DE ACCESO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria Math", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuario");

        TextUser.setEditable(false);
        TextUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TextUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUserActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contraseña");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Confirmar Contraseña");

        BtnGuardar.setBackground(new java.awt.Color(0, 102, 255));
        BtnGuardar.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        BtnGuardar.setText("GUARDAR");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        TextPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        PassNO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PassNO.setForeground(new java.awt.Color(255, 51, 51));
        PassNO.setText("CONTRASEÑAS NO COINCIDEN");

        TextPassOK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextPassOK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextPassOKKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout PanelDALayout = new javax.swing.GroupLayout(PanelDA);
        PanelDA.setLayout(PanelDALayout);
        PanelDALayout.setHorizontalGroup(
            PanelDALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDALayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(PanelDALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDALayout.createSequentialGroup()
                        .addComponent(PassNO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(PanelDALayout.createSequentialGroup()
                        .addGroup(PanelDALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDALayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(31, 31, 31)
                                .addComponent(TextPassOK, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelDALayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(95, 95, 95)
                                .addComponent(TextPass, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelDALayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(120, 120, 120)
                                .addComponent(TextUser, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(166, 166, 166))))
        );
        PanelDALayout.setVerticalGroup(
            PanelDALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDALayout.createSequentialGroup()
                .addGroup(PanelDALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelDALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDALayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6))
                    .addComponent(TextPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TextPassOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassNO)
                    .addComponent(BtnGuardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(PanelDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 265, 612, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/glogloadmin.jpg"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, -80, 1000, 740));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        JOptionPane.showMessageDialog(this, "Se procederá a revisar el registro del nuevo Administrador.");
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void TextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNameActionPerformed

    private void TextApeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextApeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextApeActionPerformed

    private void TextDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDNIActionPerformed

    private void TextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEmailActionPerformed

    private void TextCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCelActionPerformed

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
        PanelDA.setVisible(false);
        BtnNuevo.setVisible(false);
        BtnGuardar.setVisible(false);
        PassNO.setVisible(false);
        BtnGenerar.setVisible(false);
        TextName.setText("");
        TextApe.setText("");
        TextCel.setText("");
        TextDNI.setText("");
        TextEmail.setText("");
        jTFEdad.setText("");
        TextUser.setText("");
        TextPass.setText("");
        TextPassOK.setText("");
        jDCFecha.setCalendar(null);
    }//GEN-LAST:event_BtnNuevoActionPerformed

    private void TextUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUserActionPerformed

    private void BtnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGenerarActionPerformed
        int edad = cuantaEdad(jDCFecha.getDate());
        String name = TextName.getText();
        String ape = TextApe.getText();
        String cel = TextCel.getText();
        String DNI = TextDNI.getText();
        String email = TextEmail.getText();
        String usuario;
        boolean completo = false;
        completo = datosCompletos(name, ape, cel, DNI, email);
        if(completo){
            if(edad > 17){
            PanelDA.setVisible(true);
            BtnNuevo.setVisible(true);
            usuario = CrearUsuario(name, ape);
            TextUser.setText(""+usuario);
        }
            else{
                JOptionPane.showMessageDialog(this, "Se requiere ser mayor de edad para ser administrador.");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Datos incompletos.");
        }
    }//GEN-LAST:event_BtnGenerarActionPerformed

    private void jDCFechaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDCFechaPropertyChange
        // TODO add your handling code here:
        try {
            jTFEdad.setText(com.systemjaade.edad.util.MetodoGenericos.edad(jDCFecha.getDate()));
            BtnGenerar.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jDCFechaPropertyChange

    private void jTFEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFEdadActionPerformed

    private void TextPassOKKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextPassOKKeyReleased
        String pass, passOK;
        pass = TextPass.getText();
        passOK = TextPassOK.getText();
        if(passOK.equals(pass)){
            BtnGuardar.setVisible(true);
            PassNO.setVisible(false);
        }
        else{
            BtnGuardar.setVisible(false);
            PassNO.setVisible(true);
        }
    }//GEN-LAST:event_TextPassOKKeyReleased
    
    public String CrearUsuario(String name, String ape) {
        String usuario;
        char[] Ncaracter = name.toCharArray();
        char[] Acaracter = ape.toCharArray();
        usuario = "" + Ncaracter[0] + Ncaracter[1] + Ncaracter[2] + "." + Acaracter[0] + Acaracter[1] + Acaracter[2];
        return usuario;
    }
    public int cuantaEdad (Date fecha_nacimiento){
    int edad;
    LocalDate fecha_nacimientoLD = DateUtils.asLocalDate(fecha_nacimiento);
    LocalDate hoy = LocalDate.now();
    Period periodo = Period.between(fecha_nacimientoLD, hoy);
    edad =  periodo.getYears();
    return edad;
  }
    
    private boolean datosCompletos(String name, String ape, String cel, String DNI, String email) {
        return (!"".equals(name)) && (!"".equals(ape)) && (!"".equals(cel)) && (!"".equals(DNI)) && (!"".equals(email));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGenerar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JPanel PanelDA;
    private javax.swing.JPanel PanelDP;
    private javax.swing.JLabel PassNO;
    private javax.swing.JTextField TextApe;
    private javax.swing.JTextField TextCel;
    private javax.swing.JTextField TextDNI;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextName;
    private javax.swing.JPasswordField TextPass;
    private javax.swing.JPasswordField TextPassOK;
    private javax.swing.JTextField TextUser;
    private com.toedter.calendar.JDateChooser jDCFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTFEdad;
    // End of variables declaration//GEN-END:variables

        
}
