/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tabajo;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PERSONAL
 */
public class Exe extends javax.swing.JPanel {
    DefaultTableModel modelo;
    /**
     * Creates new form Exe
     */
    public Exe() {
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Tipo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Req. Maquina");
        modelo.addColumn("#Maquina");
        modelo.addColumn("Series");
        this.tabla.setModel(modelo);
        
        cbo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoExe = new javax.swing.ButtonGroup();
        Maquina = new javax.swing.ButtonGroup();
        PanelDP = new javax.swing.JPanel();
        PanelDP1 = new javax.swing.JPanel();
        rbta = new javax.swing.JRadioButton();
        rbtb = new javax.swing.JRadioButton();
        rbtc = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtexe = new javax.swing.JTextField();
        PanelDP2 = new javax.swing.JPanel();
        rbtsi = new javax.swing.JRadioButton();
        rbtno = new javax.swing.JRadioButton();
        txtmaq = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbo = new javax.swing.JComboBox();
        lblpic = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtseries = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelDP.setBackground(new java.awt.Color(0, 0, 0,100));
        PanelDP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresar Ejercicio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria Math", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        PanelDP1.setBackground(new java.awt.Color(0, 0, 0,100));
        PanelDP1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIPO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria Math", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        PanelDP1.setForeground(new java.awt.Color(255, 255, 255));

        TipoExe.add(rbta);
        rbta.setForeground(new java.awt.Color(255, 255, 255));
        rbta.setText("A-Pierna/Gluteos");

        TipoExe.add(rbtb);
        rbtb.setForeground(new java.awt.Color(255, 255, 255));
        rbtb.setText("B-Pecho/Triceps");

        TipoExe.add(rbtc);
        rbtc.setForeground(new java.awt.Color(255, 255, 255));
        rbtc.setText("C-Espalda/Biceps");
        rbtc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDP1Layout = new javax.swing.GroupLayout(PanelDP1);
        PanelDP1.setLayout(PanelDP1Layout);
        PanelDP1Layout.setHorizontalGroup(
            PanelDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDP1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbta)
                    .addComponent(rbtb)
                    .addComponent(rbtc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDP1Layout.setVerticalGroup(
            PanelDP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDP1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbta)
                .addGap(18, 18, 18)
                .addComponent(rbtb)
                .addGap(18, 18, 18)
                .addComponent(rbtc)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descripcion");

        PanelDP2.setBackground(new java.awt.Color(0, 0, 0,100));
        PanelDP2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Maquina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria Math", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        PanelDP2.setForeground(new java.awt.Color(255, 255, 255));

        Maquina.add(rbtsi);
        rbtsi.setForeground(new java.awt.Color(255, 255, 255));
        rbtsi.setText("Si");
        rbtsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtsiActionPerformed(evt);
            }
        });

        Maquina.add(rbtno);
        rbtno.setForeground(new java.awt.Color(255, 255, 255));
        rbtno.setText("No");
        rbtno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnoActionPerformed(evt);
            }
        });

        txtmaq.setText("##");
        txtmaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDP2Layout = new javax.swing.GroupLayout(PanelDP2);
        PanelDP2.setLayout(PanelDP2Layout);
        PanelDP2Layout.setHorizontalGroup(
            PanelDP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDP2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PanelDP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDP2Layout.createSequentialGroup()
                        .addComponent(rbtno)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelDP2Layout.createSequentialGroup()
                        .addComponent(rbtsi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtmaq, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PanelDP2Layout.setVerticalGroup(
            PanelDP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDP2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtsi)
                    .addComponent(txtmaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Elegir Maquina");

        cbo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Maquina", "Maquina #1", "Maquina #2", "Maquina #3", "Maquina #4", "Maquina #5", "Maquina #6" }));
        cbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboActionPerformed(evt);
            }
        });

        lblpic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblpic.setMaximumSize(new java.awt.Dimension(240, 245));
        lblpic.setMinimumSize(new java.awt.Dimension(240, 245));
        lblpic.setPreferredSize(new java.awt.Dimension(240, 245));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Series");

        javax.swing.GroupLayout PanelDPLayout = new javax.swing.GroupLayout(PanelDP);
        PanelDP.setLayout(PanelDPLayout);
        PanelDPLayout.setHorizontalGroup(
            PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDPLayout.createSequentialGroup()
                .addGroup(PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PanelDP2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelDP1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDPLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(txtexe, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDPLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(cbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblpic, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(PanelDPLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtseries, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelDPLayout.setVerticalGroup(
            PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDPLayout.createSequentialGroup()
                .addGroup(PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDPLayout.createSequentialGroup()
                        .addGroup(PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(6, 6, 6)
                        .addGroup(PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtseries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDPLayout.createSequentialGroup()
                                .addGroup(PanelDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblpic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelDPLayout.createSequentialGroup()
                        .addComponent(PanelDP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelDP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(PanelDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 620, 320));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 620, 150));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/FONDO.png"))); // NOI18N
        add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void rbtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtcActionPerformed

    private void rbtnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnoActionPerformed
        // TODO add your handling code here:
        txtmaq.setVisible(false);
        cbo.setVisible(false);
    }//GEN-LAST:event_rbtnoActionPerformed

    private void txtmaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaqActionPerformed

    private void rbtsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtsiActionPerformed
        // TODO add your handling code here:
        txtmaq.setVisible(true);
        cbo.setVisible(true);
    }//GEN-LAST:event_rbtsiActionPerformed

    private void cboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboActionPerformed
        // TODO add your handling code here:
        int img=cbo.getSelectedIndex();
        switch(img){
            case 1:
                ImageIcon imagen = new ImageIcon(this.getClass().getResource("/imagen/Maquina1.png"));
                lblpic.setIcon(imagen);
                txtexe.setText("");
                txtexe.setText("Remo Sentado");
                       
                break;
            case 2:
                ImageIcon imagen2 = new ImageIcon(this.getClass().getResource("/imagen/Maquina2.png"));
                lblpic.setIcon(imagen2);
                txtexe.setText("");
                txtexe.setText("Prensa");

                break;
            case 3:
                ImageIcon imagen3 = new ImageIcon(this.getClass().getResource("/imagen/Maquina3.png"));
                lblpic.setIcon(imagen3);
                txtexe.setText("");
                txtexe.setText("Triceps en Polea");
                break;
            case 4:
                ImageIcon imagen4 = new ImageIcon(this.getClass().getResource("/imagen/Maquina4.png"));
                lblpic.setIcon(imagen4);
                txtexe.setText("");
                txtexe.setText("Abduccion de Piernas");
                       
                break;
            case 5:
                ImageIcon imagen5 = new ImageIcon(this.getClass().getResource("/imagen/Maquina5.png"));
                lblpic.setIcon(imagen5);
                txtexe.setText("");
                txtexe.setText("Fly en Maquina");

                break;
            case 6:
                ImageIcon imagen6 = new ImageIcon(this.getClass().getResource("/imagen/Maquina6.png"));
                lblpic.setIcon(imagen6);
                txtexe.setText("");
                txtexe.setText("Jalon en Polea");
                break;
        }
    }//GEN-LAST:event_cboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Maquina.add(rbtsi);
        Maquina.add(rbtno);
        TipoExe.add(rbta);
        TipoExe.add(rbtb);
        TipoExe.add(rbtc);
        

        String []info = new String[5];
        if(rbta.isSelected()){
            info[0]="A";
        }
        else if(rbtb.isSelected()){
            info[0]="B";
        }else if(rbtc.isSelected()){
            info[0]="C";
        }else{
            info[0]="";
        }
        info[1]=txtexe.getText();
        if(rbtsi.isSelected()){
            info[2]="Si";
            info[3]=txtmaq.getText();
        }
        else if(rbtno.isSelected()){
            info[2]="Si";
            info[3]="--";
        }else{
            info[2]="";
            info[3]="";
        }
        info[4]=txtseries.getText();
        
        
        if(info[0].equals("")||info[1].equals("")||info[2].equals("")||info[3].equals("")||info[3].equals("")){
            JOptionPane.showMessageDialog(null,"Los campos no pueden estar vacios");
            
        }else 
            modelo.addRow(info);

            txtexe.setText("");
            txtmaq.setText("");
            txtseries.setText("");
            
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.ButtonGroup Maquina;
    private javax.swing.JPanel PanelDP;
    private javax.swing.JPanel PanelDP1;
    private javax.swing.JPanel PanelDP2;
    private static javax.swing.ButtonGroup TipoExe;
    private javax.swing.JComboBox cbo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblpic;
    private javax.swing.JRadioButton rbta;
    private javax.swing.JRadioButton rbtb;
    private javax.swing.JRadioButton rbtc;
    private javax.swing.JRadioButton rbtno;
    private javax.swing.JRadioButton rbtsi;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtexe;
    private javax.swing.JTextField txtmaq;
    private javax.swing.JTextField txtseries;
    // End of variables declaration//GEN-END:variables
}
