/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tabajo;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author PERSONAL
 */


public class MenuAdmi extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmi
     */
    public MenuAdmi() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BigPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAgregarAdmi = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnPagosPendientes = new javax.swing.JButton();
        btnAgregarCliente = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnExe = new javax.swing.JButton();
        btnexit = new org.edisoncor.gui.button.ButtonPopup();
        content = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BigPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BigPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 80));

        btnAgregarAdmi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/gym_icon_124498.png"))); // NOI18N
        btnAgregarAdmi.setText("Agregar Admi");
        btnAgregarAdmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAdmiActionPerformed(evt);
            }
        });
        BigPanel.add(btnAgregarAdmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, 50));

        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/bench_press_gym_fitness_equipment_sport_icon_224865.png"))); // NOI18N
        btnProveedores.setText("Proveedores");
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        BigPanel.add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 180, 50));

        btnPagosPendientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/search_icon_129452.png"))); // NOI18N
        btnPagosPendientes.setText("Pagos Pendientes");
        btnPagosPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosPendientesActionPerformed(evt);
            }
        });
        BigPanel.add(btnPagosPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 180, 50));

        btnAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/business_application_addmale_useradd_insert_add_user_client_2312.png"))); // NOI18N
        btnAgregarCliente.setText("Agregar Clientes");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });
        BigPanel.add(btnAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, 50));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/business_man_usersearch_thesearch_theclient_2356.png"))); // NOI18N
        btnBuscar.setText("Buscar Cliente");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        BigPanel.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 180, 50));

        btnExe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/kettlebell_equipment_gym_fitness_icon_224876.png"))); // NOI18N
        btnExe.setText("Lista de Ejercicios");
        btnExe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExeActionPerformed(evt);
            }
        });
        BigPanel.add(btnExe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 180, 50));

        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/exit48.png"))); // NOI18N
        btnexit.setBorderPainted(false);
        btnexit.setContentAreaFilled(false);
        btnexit.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/exit48.png"))); // NOI18N
        btnexit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/exit.png"))); // NOI18N
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        BigPanel.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 60, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/perfil.png"))); // NOI18N

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, Short.MAX_VALUE)
        );

        BigPanel.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 700, 570));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo-pared-ladrillo-textura-negro_53876-63590.jpg"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(700, 570));
        BigPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 570));

        getContentPane().add(BigPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        Buscar p2 = new Buscar();
        ShowPanel(p2);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnPagosPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosPendientesActionPerformed
        // TODO add your handling code here:
        Pagos p6 = new Pagos();
        ShowPanel(p6);
    }//GEN-LAST:event_btnPagosPendientesActionPerformed

    private void btnExeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExeActionPerformed
        // TODO add your handling code here:
        Exe p5 = new Exe();
        ShowPanel(p5);
    }//GEN-LAST:event_btnExeActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        // TODO add your handling code here:
        AgregarCliente p1 = new AgregarCliente();
        ShowPanel(p1);
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnAgregarAdmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAdmiActionPerformed
        // TODO add your handling code here:
        AgregarAdmi p3 = new AgregarAdmi();
        ShowPanel(p3);
    }//GEN-LAST:event_btnAgregarAdmiActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        // TODO add your handling code here:
        Proveedores p4 = new Proveedores();
        ShowPanel(p4);
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed
    private void ShowPanel(JPanel p){
        p.setSize(700,570);
        p.setLocation(0,0);
        
        content.removeAll();
        content.add(p,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
        
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BigPanel;
    private javax.swing.JButton btnAgregarAdmi;
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExe;
    private javax.swing.JButton btnPagosPendientes;
    private javax.swing.JButton btnProveedores;
    private org.edisoncor.gui.button.ButtonPopup btnexit;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
